default:

  # global random seed
  seed: 12345

  normal:
    # number of samples
    NSAMPLES: 1000
    # mean of the normal distribution
    MEAN: 0.0
    # standard deviation of the normal distribution
    STDDEV: 1.0

  regression:
    # slope of regression
    SLOPE: 2.0
    # white noise variance
    NOISE: 2.0

  plot:
    # width
    WIDTH: 10
    # height
    HEIGHT: 6