default:

  # global random seed
  SEED: 12345

  NORMAL:
    # number of samples
    NSAMPLES: 1000
    # mean of the normal distribution
    MEAN: 0.0
    # standard deviation of the normal distribution
    STDDEV: 1.0

  REGRESSION:
    # slope of regression
    SLOPE: 2.0
    # white noise variance
    NOISE: 2.0

  PLOT:
    # width
    WIDTH: 10
    # height
    HEIGHT: 6

  PATH:
    # path to save figures
    FIGURE: "outputs/figures"
    # path to save models
    MODEL: "outputs/models"
    # path to save data
    DATA: "data"